# Configuration for support-requests - https://github.com/dessant/support-requests
name: Support Stack Overflow

on:
  issues:
    types: [labeled, unlabeled, reopened]

permissions: {}

jobs:
  mark-support:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: dessant/support-requests@b1303caf4438e66dea1130aa4c30189dc28e690d # v3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Label used to mark issues as support requests
          support-label: 'support: Stack Overflow'
          # Comment to post on issues marked as support requests. Add a link
          # to a support page, or set to `false` to disable
          issue-comment: |
            ðŸ‘‹ Thanks for using MUI Core!

            We use GitHub issues exclusively as a bug and feature requests tracker, however,
            this issue appears to be a support request.

            For support, please check out https://mui.com/getting-started/support/. Thanks!

            If you have a question on Stack Overflow, you are welcome to link to it here, it might help others.
            If your issue is subsequently confirmed as a bug, and the report follows the issue template, it can be reopened.
          close-issue: true
          lock-issue: false
